service: unity-on-demand-api-trigger

frameworkVersion: '3'

configValidationMode: error

package:
  individually: true

provider:
  name: aws
  runtime: python3.9
  deploymentMethod: direct
  httpApi:
    cors: true
  region: ${opt:region, "us-west-2"}
  deploymentBucket:
    skipPolicySetup: true
  stage: ${opt:stage, "dev"}
  iam:
    role:
      permissionsBoundary: arn:aws:iam::${aws:accountId}:policy/${param:permissionsBoundaryPolicyName}

functions:
  app:
    package:
      patterns:
        - "!test_client.*"
        - "!deploy*.sh"
        - "!.virtualenv/**"
        - "!env/**"
        - "!__pycache__/**"
        - "!triggers/**"
        - "!update_client.sh"
        - "!*.code-workspace"
    handler: app.lambda_handler
    environment:
      STAGE: ${self:provider.stage}
      OD_API_URL: ${param:od_api_url}

plugins:
  - serverless-python-requirements
