service: unity-on-demand-api

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.9
  deploymentMethod: direct
  stage: dev
  region: ${opt:region, "us-west-2"}
  deploymentBucket:
    skipPolicySetup: true

  iam:
    role:
      name: unity-on-demand-api-lambda-role
      permissionsBoundary: arn:aws:iam::${aws:accountId}:policy/${param:permissionsBoundaryPolicyName}

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements
